// Generated by https://quicktype.io

export interface PokeAPIResponse {
  _id: string
  no: number
  name: string
  image: string
  generation: number
  types: string[]
  source: string
  evolutions: string[]
  files: string[]
  __v: number
}
